apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: blazor-container
        image: kakashidota/blazordemo:latest
        ports:
        - containerPort: 80